{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# [Coursera Machine Learning MOOC by Andrew Ng](https://www.coursera.org/learn/machine-learning) \n",
    "# Python Programming Assignments\n",
    "\n",
    "![](machinelearning.jpg)\n",
    "\n",
    "This repositry contains the python versions of the programming assignments for the [Machine Learning online class](https://www.coursera.org/learn/machine-learning) taught by Professor Andrew Ng. This is perhaps the most popular introductory online machine learning class. In addition to being popular, it is also one of the best Machine learning classes any interested student can take to get started with machine learning. An unfortunate aspect of this class is that the programming assignments are in MATLAB or OCTAVE, probably because this class was made before python became the go-to language in machine learning.\n",
    "\n",
    "The Python machine learning ecosystem has grown exponentially in the past few years, and is still gaining momentum. I suspect that many students who want to get started with their machine learning journey would like to start it with Python also. It is for those reasons I have decided to re-write all the programming assignments in Python, so students can get acquainted with its ecosystem from the start of their learning journey. \n",
    "\n",
    "These assignments work seamlessly with the class and do not require any of the materials published in the MATLAB assignments. Here are some new and useful features for these sets of assignments: \n",
    "\n",
    "- The assignments use [Jupyter Notebook](http://jupyter-notebook-beginner-guide.readthedocs.io/en/latest/what_is_jupyter.html), which provides an intuitive flow easier than the original MATLAB/OCTAVE assignments.\n",
    "- The original assignment instructions have been completely re-written and the parts which used to reference MATLAB/OCTAVE functionality have been changed to reference its `python` counterpart.\n",
    "- The re-written instructions are now embedded within the Jupyter Notebook along with the `python` starter code. For each assignment, all work is done solely within the notebook.\n",
    "- The `python` assignments can be submitted for grading. They were tested to work perfectly well with the original Coursera grader that is currently used to grade the MATLAB/OCTAVE versions of the assignments. \n",
    "- After each part of a given assignment, the Jupyter Notebook contains a cell which prompts the user for submitting the current part of the assignment for grading.  \n",
    "\n",
    " ## Online workspace\n",
    " \n",
    " You can work on the assignments in an online workspace called [Deepnote](https://www.deepnote.com/). This allows you to play around with the code and access the assignments from your browser. [<img height=\"22\"  src=\"https://beta.deepnote.com/buttons/launch-in-deepnote.svg\">](https://beta.deepnote.com/launch?template=data-science&url=https%3A%2F%2Fgithub.com%2Fdibgerge%2Fml-coursera-python-assignments)\n",
    "\n",
    "## Downloading the Assignments\n",
    "\n",
    "To get started, you can start by either downloading a zip file of these assignments by clicking on the `Clone or download` button. If you have `git` installed on your system, you can clone this repository using : \n",
    "\n",
    "    clone https://github.com/dibgerge/ml-coursera-python-assignments.git\n",
    "    \n",
    "Each assignment is contained in a separate folder. For example, assignment 1 is contained within the folder `Exercise1`. Each folder contains two files: \n",
    " - The assignment `jupyter` notebook, which has a `.ipynb` extension. All the code which you need to write will be written within this notebook.\n",
    " - A python module `utils.py` which contains some helper functions needed for the assignment. Functions within the `utils` module are called from the python notebook. You do not need to modify or add any code to this file.\n",
    "\n",
    "## Requirements \n",
    "\n",
    "These assignments has been tested and developed using the following libraries: \n",
    "\n",
    "    - python==3.6.4\n",
    "    - numpy==1.13.3\n",
    "    - scipy==1.0.0\n",
    "    - matplotlib==2.1.2\n",
    "    - jupyter==1.0.0\n",
    "    - jupyter-client==5.0.1\n",
    "    \n",
    "We recommend using at least these versions of the required libraries or later. Python 2 is not supported. \n",
    "    \n",
    "## Python Installation\n",
    "\n",
    "We highly recommend using anaconda for installing python. [Click here](https://www.anaconda.com/download/) to go to Anaconda's download page. Make sure to download Python 3.6 version.\n",
    "If you are on a windows machine:\n",
    " - Open the executable after download is complete and follow instructions.\n",
    " - Once installation is complete, open `Anaconda prompt` from the start menu. This will open a terminal with python enabled.\n",
    " \n",
    " If you are on a linux machine: \n",
    " \n",
    " - Open a terminal and navigate to the directory where Anaconda was downloaded. \n",
    " - Change the permission to the downloaded file so that it can be executed. So if the downloaded file name is `Anaconda3-5.1.0-Linux-x86_64.sh`, then use the following command:\n",
    " \n",
    "      `chmod a+x Anaconda3-5.1.0-Linux-x86_64.sh`\n",
    " \n",
    " - Now, run the installation script using `./Anaconda3-5.1.0-Linux-x86_64.sh`, and follow installation instructions in the terminal.\n",
    " \n",
    " \n",
    "Once you have installed python, create a new python environment will all the requirements using the following command: \n",
    "\n",
    "    conda env create -f environment.yml\n",
    " \n",
    "After the new environment is setup, activate it using (windows)\n",
    "\n",
    "    activate machine_learning\n",
    "   \n",
    "or if you are on a linux machine\n",
    "\n",
    "    source activate machine_learning \n",
    "\n",
    "Now we have our python environment all set up, we can start working on the assignments. To do so, navigate to the directory where the assignments were installed, and launch the jupyter notebook from the terminal using the command\n",
    "\n",
    "    jupyter notebook\n",
    "\n",
    "This should automatically open a tab in the default browser. To start with assignment 1, open the notebook `./Exercise1/exercise1.ipynb`. \n",
    "\n",
    "## Python Tutorials\n",
    "\n",
    "If you are new to python and to `jupyter` notebooks, no worries! There is a plethora of tutorials and documentation to get you started. Here are a few links which might be of help:\n",
    "\n",
    "- [Python Programming](https://pythonprogramming.net/introduction-to-python-programming/): A turorial with videos about the basics of python. \n",
    "\n",
    "- [Numpy and matplotlib tutorial](http://cs231n.github.io/python-numpy-tutorial/): We will be using numpy extensively for matrix and vector operations. This is great tutorial to get you started with using numpy and matplotlib for plotting.\n",
    "\n",
    "- [Jupyter notebook](https://medium.com/codingthesmartway-com-blog/getting-started-with-jupyter-notebook-for-python-4e7082bd5d46): Getting started with the jupyter notebook. \n",
    "\n",
    "- [Python introduction based on the class's MATLAB tutorial](https://github.com/mstampfer/Coursera-Stanford-ML-Python/blob/master/Coursera%20Stanford%20ML%20Python%20wiki.ipynb): This is the equivalent of class's MATLAB tutorial, in python.\n",
    "\n",
    "\n",
    "## Caveats and tips\n",
    "\n",
    "- In many of the exercises, the regularization parameter $\\lambda$ is denoted as the variable name `lambda_`, notice the underscore at the end of the name. This is because `lambda` is a reserved python keyword, and should never be used as a variable name.\n",
    "\n",
    "-  In `numpy`, the function `dot` is used to perform matrix multiplication. The operation '*' only does element-by-element multiplication (unlike MATLAB). If you are using python version 3.5+, the operator '@' is the new matrix multiplication, and it is equivalent to the `dot` function.\n",
    "\n",
    "## Acknowledgements\n",
    "\n",
    "- I would like to thank professor Andrew Ng and the crew of the Stanford Machine Learning class on Coursera for such an awesome class. \n",
    "\n",
    "- Some of the material used, especially the code for submitting assignments for grading is based on [`mstampfer`'s](https://github.com/mstampfer/Coursera-Stanford-ML-Python) python implementation of the assignments. \n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.5"
  },
  "varInspector": {
   "cols": {
    "lenName": 16,
    "lenType": 16,
    "lenVar": 40
   },
   "kernels_config": {
    "python": {
     "delete_cmd_postfix": "",
     "delete_cmd_prefix": "del ",
     "library": "var_list.py",
     "varRefreshCmd": "print(var_dic_list())"
    },
    "r": {
     "delete_cmd_postfix": ") ",
     "delete_cmd_prefix": "rm(",
     "library": "var_list.r",
     "varRefreshCmd": "cat(var_dic_list()) "
    }
   },
   "types_to_exclude": [
    "module",
    "function",
    "builtin_function_or_method",
    "instance",
    "_Feature"
   ],
   "window_display": false
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
